/*
pipeline {
  agent none
  stages {
    stage('Stage1') {
      agent any
      steps {
        sh 'echo "Stage1"'
      }
    }
    stage('Approve') {
      steps {
        checkpoint 'Approval'
        input 'Approve?'
      }
    }
    stage('Stage2') {
      agent any
      steps {
        sh 'echo "Stage2"'
      }
    }
  }
}
*/
stage 'aaa'; echo 'ran'; checkpoint('bob'); stage 'bbb'; echo '2';
