pipeline {
  agent none
  stages {
    stage('Stage1') {
      agent any
      steps {
        sh 'echo "Stage1"'
      }
    }
    stage('Approve') {
      steps {
        checkpoint 'Approval'
        input 'Approve?'
      }
    }
    stage('Stage2') {
      agent any
      steps {
        sh 'echo "Stage2"'
      }
    }
  }
}